force-app/main/default/objects/Account/fields/LastReviewedDate__c.field-meta.xml
<CustomField>
    <fullName>LastReviewedDate__c</fullName>
    <label>Last Reviewed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Classroom__c/Classroom__c.object-meta.xml
<CustomObject>
    <label>Classroom</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Classroom Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Classrooms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Classroom__c/fields/Standard__c.field-meta.xml
<CustomField>
    <fullName>Standard__c</fullName>
    <label>Standard</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>ADM-{0000000}</displayFormat>
        <label>Admission Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Studends</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Classroom__c.field-meta.xml
<CustomField>
    <fullName>Classroom__c</fullName>
    <label>Classroom</label>
    <referenceTo>Classroom__c</referenceTo>
    <relationshipLabel>Studends</relationshipLabel>
    <relationshipName>Studends</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DmlDemo2.cls
public class DmlDemo2 {
    public static void dmlAssignment4() {
        Classroom__c c6 = [select id, Standard__c from Classroom__c where Standard__c = 6 limit 1];

        Student__c s1 = new Student__c();
        s1.First_Name__c = 'Joe';
        s1.Last_Name__c = 'Bardin';
        s1.Age__c = 11;
        s1.Classroom__c = c6.id; //do you all get this?
        insert s1;
        system.debug('new student id is ' + s1.Id);
    }

    public static void dmlUpdate1() {
        account acc = new account();
        acc.Name = 'Salesforce';
        acc.Website = 'salesforce.com';
        insert acc;

        //set diffent values for some of the fields
        acc.name = 'Yoll';
        acc.Website = 'yoll.io';
        //dml to update
        update acc;

    }

    public static void dmlUpdate2(){
        //update acc record which is present in the org.
        account acc = [select id, name, website, active__c from account order by createddate desc limit 1];

        system.debug('before update dml: ' + acc);
        acc.name = 'Timex';
        acc.Website = 'timex.com';
        update acc;
        system.debug('after update dml: ' + acc);
    }

    //Don't do this at home or anywhere else also. 
    public static void dmlInsertMultipleWrong() {
        for (Integer i = 0; i < 75; i++) {
            account a = new account();
            a.Name = 'new acc ' + i;
            //never write DML inside loop
            insert a;
        }
    }
    public static void dmlInsertMultipleRight() {
        List<account> listAcc = new list<account>();

        for (Integer i = 0; i < 155; i++) {
            account a = new account();
            a.Name = 'new acc ' + i;
            listAcc.add(a);
        }
        insert listAcc;
    }

    //update account active field to No if it is null
    public static void dmlUpdateBulk1() {
        //maximum records we can fetch using SOQL is 50k. 
        list<account> listAcc = [select id, name, active__c from account]; //185
        list<account> updateAcc = new list<account>();
        
        for (account eachAcc : listAcc) {
            //150
            if (eachAcc.Active__c == 'No') {
                eachAcc.Active__c = '';
                updateAcc.add(eachAcc);
            }
        }

        update updateAcc;//we updated all 150 records
        system.debug(listAcc.size());
    }

    public static void dmlAssignment9() {
        account acc= new account ();
        acc.Name='ABC Corp';
        insert acc;
        //after insertion, we will GET the ID.

        List<contact> createContacts = new list<contact>{
            new contact(FirstName = 'John', LastName = 'Mayor', accountid = acc.Id),
            new contact(FirstName = 'Jane', LastName = 'Mayor', accountid = acc.Id),
            new contact(FirstName = 'Manny', LastName = 'Mayor', accountid = acc.Id),
            new contact(FirstName = 'Phil', LastName = 'Mayor', accountid = acc.Id)
        };
        insert createContacts;
        
    }
    public static void dmlAssignment9pt2() {
        list<contact> allContacts = [select id, firstname, birthdate from contact where account.name = 'ABC Corp'];
        for (contact eachContact : allContacts) {
            eachContact.LastReviewedDate__c = date.newInstance(1990, 01, 01);
        }
        update allContacts;
    }

}