force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Department Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Department_Phone__c.field-meta.xml
<CustomField>
    <fullName>Department_Phone__c</fullName>
    <label>Department Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{0000}</displayFormat>
        <label>EmployeeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmployeeTriggerHandler.cls
public class EmployeeTriggerHandler {
    public static void updateDeptarmentPhone(List<employee__c> empTriggerNew, Map<id, employee__c> empTriggerNewMap, List<employee__c> empTriggerOld, Map<id, employee__c> empTriggerOldMap) {
        //get department ids
        //set<id> deptIds = new set<id>();
        map<id, string> depIdsPhone = new map<id, string>();
        for (Employee__c newEmp : empTriggerNew) {
            if (newEmp.Department__c != null) {
                //deptIds.add(newEmp.Department__c);
                //adding dept id and phone which we want to update in that deparment
                depIdsPhone.put(newEmp.Department__c, newEmp.department_phone__c);
            }
        }

        List<Department__c> allDepts = [select id, department_phone__c from Department__c where id in :depIdsPhone.keySet()];

        for (Department__c eachDep : allDepts) {
            eachDep.department_phone__c = depIdsPhone.get(eachDep.Id);
        }
        update allDepts;//will call department trigger.
    }
}