force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Department Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{0000}</displayFormat>
        <label>EmployeeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/JoinDate__c.field-meta.xml
<CustomField>
    <fullName>JoinDate__c</fullName>
    <label>JoinDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SoqlDemo3.cls
public class SoqlDemo3 {
    public static void aggregateSoql1(){
        List<aggregateresult> listAg = [select country__c, count(id), sum(salary__c) from employee__c group by country__c];
        //we want to print each result one by one
        for(aggregateresult ag: listAg){
            system.debug('ag: ' + ag);
            system.debug('country: ' + ag.get('country__c'));
            system.debug('number of records: ' + ag.get('expr0'));//expression0
            system.debug('sum of salary: ' + ag.get('expr1'));//expression1
        }
    }
    public static void aggregateSoql2(){
        List<aggregateresult> listAg = [select Department__r.name__c dept, count(id), sum(salary__c) from employee__c group by Department__r.name__c];
        //we want to print each result one by one
        for(aggregateresult ag: listAg){
            system.debug('ag: ' + ag);
            system.debug('dept: ' + ag.get('dept'));
            system.debug('number of records: ' + ag.get('expr0'));//expression0
            system.debug('sum of salary: ' + ag.get('expr1'));//expression1
        }
    }

    public static void soqlExample3() {
        List<Employee__c> listEmp = [select id, first_name__c, Last_Name__c, Salary__c, Country__c, JoinDate__c from Employee__c];
        for (Employee__c emp : listEmp) {
            system.debug(emp.First_Name__c + emp.Last_Name__c);
            system.debug(emp.Salary__c);
        }
    }

    public static void dynamicSoql1(list<string> fieldNames) {
        string query = 'select Id ';

        for (string eachField : fieldNames) {
            query += ',' + eachField;
        }

        query += ' from Employee__c';
        system.debug('FINAL QUERY IS ==> ' + query);

        List<Employee__c> listEMp = database.query(query);

        for (Employee__c emp : listEmp) {
            system.debug(emp);
        }
    }

    public static void dynamicSoql2(list<string> fieldNames, string sObjectName) {
        string query = 'select Id ';

        for (string eachField : fieldNames) {
            query += ',' + eachField;
        }

        query += ' from ' + sObjectName;
        system.debug('FINAL QUERY IS ==> ' + query);

        List<SObject> listSO = database.query(query);
        
        for (SObject eachRec : listSO) {
            system.debug(eachRec);
            
            for (string eachField : fieldNames) {
                system.debug('===> fieldName: ' + eachField + ', value : ' + eachRec.get(eachField));
            }
        }
    }
}