force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Department Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{0000}</displayFormat>
        <label>EmployeeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserModeDemo.cls
public with sharing class UserModeDemo {

    public static void createAcc1() {
        Account acc = new account(name = 'test user mode', Website = 'www.user.mode');
        insert as User acc;
    }
    public static void createAcc2() {
        Account acc = new account(name = 'test user mode wo website', Industry = 'Energy', rating = 'Hot');
        insert as User acc;
    }

    public static void createAcc3() {
        Account acc = new account(name = 'test user mode', Website = 'www.user.mode');
        database.SaveResult ds = database.insert(acc, AccessLevel.USER_MODE);
        if (ds.isSuccess()) {
            system.debug('successfully inserted.');
        } else {
            system.debug('error it is');
        }
    }
    public static void createAcc4() {
        Account acc = new account(name = 'test user mode wo website', Industry = 'Energy', rating = 'Hot');
        database.SaveResult ds = database.insert(acc, false, AccessLevel.USER_MODE);
        if (ds.isSuccess()) {
            system.debug('successfully inserted.');
        } else {
            system.debug('error it is');
        }
    }

   public static void sampleAccounts() {
        List<account> allAccounts = [select id, name, website, phone from account WITH SECURITY_ENFORCED];
        system.debug(allAccounts);

   }
   public static void sampleAccounts2() {
        List<account> allAccounts = [select id, name, website, phone from account WITH USER_MODE];
        system.debug(allAccounts);

   }
   public static void sampleAccounts5() {
        string accQuery = 'select id, name, website, phone from account';
        List<SObject> allAcc = Database.query(accQuery, AccessLevel.USER_MODE);
        system.debug(allAcc);
   }
   public static void sampleAccount3() {
        List<account> allAccounts = [select id, name, website, phone from account WITH SYSTEM_MODE];
        system.debug(allAccounts);

   }
   public static void sampleEmployees() {
    List<Employee__c> allEMp = [select id, first_name__c, last_name__c, salary__c, department__c from Employee__c WITH SECURITY_ENFORCED];
        system.debug(allEMp);
   }

}