force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Department Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{0000}</displayFormat>
        <label>EmployeeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmployeeDetails.cls
public class EmployeeDetails {
    public static void forInformationTechnology(List<string> listFirstName, list<string> listLastName, list<string> listEmail) {
        //check if all three list same, else system debug error
        if (listFirstName.size() == listLastname.size() && listFirstName.size() == listEmail.size()) {
            //get information technology department

            List<Department__c> d = [select id from Department__c where name__c = 'Information Technology'];
            if (d.isEmpty()) {
                system.debug('no such department. so creating new.');
                //if you don't have IT, create that department.
                Department__c newDep = new Department__c(Name__c = 'Information Technology');
                insert newDep;
                d.add(newDep);
            }
            List<Employee__c> newEmployees = new list<Employee__c>();
            for (Integer i = 0; i < listFirstName.size(); i++) {
                Employee__c e = new Employee__c(
                    First_Name__c = listFirstName[i],
                    Last_Name__c = listLastName[i],
                    Email__c = listEmail[i],
                    Department__c = d[0].Id
                );
                newEmployees.add(e);
            }
            insert newEmployees;
        } else {
            system.debug('list sizes are not same. fix it please.');
        }
    }

    public static void forFinanceAndAccounting(List<string> listFirstName, list<string> listLastName, list<string> listEmail) {
        //check if all three list same, else system debug error
        if (listFirstName.size() == listLastname.size() && listFirstName.size() == listEmail.size()) {
            //get information technology department

            List<Department__c> d = [select id from Department__c where name__c = 'Finance And Accounting'];
            if (d.isEmpty()) {
                system.debug('no such department. so creating new.');
                //if you don't have IT, create that department.
                Department__c newDep = new Department__c(Name__c = 'Finance And Accounting');
                insert newDep;
                d.add(newDep);
            }
            List<Employee__c> newEmployees = new list<Employee__c>();
            for (Integer i = 0; i < listFirstName.size(); i++) {
                Employee__c e = new Employee__c(
                    First_Name__c = listFirstName[i],
                    Last_Name__c = listLastName[i],
                    Email__c = listEmail[i],
                    Department__c = d[0].Id
                );
                newEmployees.add(e);
            }
            insert newEmployees;
        } else {
            system.debug('list sizes are not same. fix it please.');
        }
    }

    public static void forProductionEngineering(List<string> listFirstName, list<string> listLastName, list<string> listEmail) {
        //check if all three list same, else system debug error
        if (listFirstName.size() == listLastname.size() && listFirstName.size() == listEmail.size()) {
            //get information technology department

            List<Department__c> d = [select id from Department__c where name__c = 'Production Engineering'];
            if (d.isEmpty()) {
                system.debug('no such department. so creating new.');
                //if you don't have IT, create that department.
                Department__c newDep = new Department__c(Name__c = 'Production Engineering');
                insert newDep;
                d.add(newDep);
            }
            List<Employee__c> newEmployees = new list<Employee__c>();
            for (Integer i = 0; i < listFirstName.size(); i++) {
                Employee__c e = new Employee__c(
                    First_Name__c = listFirstName[i],
                    Last_Name__c = listLastName[i],
                    Email__c = listEmail[i],
                    Department__c = d[0].Id
                );
                newEmployees.add(e);
            }
            insert newEmployees;
        } else {
            system.debug('list sizes are not same. fix it please.');
        }
    }

    public static void forQualityAssurance(List<string> listFirstName, list<string> listLastName, list<string> listEmail) {
        //check if all three list same, else system debug error
        if (listFirstName.size() == listLastname.size() && listFirstName.size() == listEmail.size()) {
            //get information technology department

            List<Department__c> d = [select id from Department__c where name__c = 'Quality Assurance'];
            if (d.isEmpty()) {
                system.debug('no such department. so creating new.');
                //if you don't have IT, create that department.
                Department__c newDep = new Department__c(Name__c = 'Quality Assurance');
                insert newDep;
                d.add(newDep);
            }
            List<Employee__c> newEmployees = new list<Employee__c>();
            for (Integer i = 0; i < listFirstName.size(); i++) {
                Employee__c e = new Employee__c(
                    First_Name__c = listFirstName[i],
                    Last_Name__c = listLastName[i],
                    Email__c = listEmail[i],
                    Department__c = d[0].Id
                );
                newEmployees.add(e);
            }
            insert newEmployees;
        } else {
            system.debug('list sizes are not same. fix it please.');
        }
    }
}