force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Department Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Department_Phone__c.field-meta.xml
<CustomField>
    <fullName>Department_Phone__c</fullName>
    <label>Department Phone</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{0000}</displayFormat>
        <label>EmployeeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/DepartmentTriggerHandler.cls
public class DepartmentTriggerHandler {
    public static boolean allEmployeeUpdated = false;

    public static void updateEmployeePhone(list<department__c> depTriggerNew, map<id, department__c> depTriggerNewMap, list<department__c> depTriggerOld, map<id, department__c> depTriggerOldMap) {
        
        //get all employees of all the updated departments

        List<Employee__c> allEmps = [select id, Department__c, department_phone__c from Employee__c where Department__c in :depTriggerNewMap.keySet()];
        system.debug('allEmps: ' + allEmps);


        for (Employee__c eachEmp : allEmps) {
            //get employee's depatment's department phone field HERE.
            department__c newDept = depTriggerNewMap.get(eachEmp.Department__c);
            eachEmp.department_phone__c = newDept.department_phone__c;
        }
        allEmployeeUpdated = true;
        update allEmps; //call employee trigger
       
    }
}