force-app/main/default/objects/Department__c/Department__c.object-meta.xml
<CustomObject>
    <label>Department</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Department Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Departments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Department__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Department__c/fields/Short_Code__c.field-meta.xml
<CustomField>
    <fullName>Short_Code__c</fullName>
    <label>Short Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>Emp-{0000}</displayFormat>
        <label>EmployeeId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Employee__c/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Department</label>
    <referenceTo>Department__c</referenceTo>
    <relationshipLabel>Employees</relationshipLabel>
    <relationshipName>Employees</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Employee__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountInfo.cls
public class AccountInfo {
    public static void showParentToChild1() {
        list<account> listAcc = [select id, name, phone,(select name, email from contacts) from account];

        for (account eachAcc : listAcc) {
            system.debug('acc name : ' + eachAcc.Name + ', acc phone: ' + eachAcc.Phone);

            list<contact> listContacts = eachAcc.Contacts;//list

            integer totalContacts = listContacts.size();
            //check if we have atleast one contact
            if (totalContacts > 0) {
                for (contact eachContact : listContacts) {
                    system.debug('contact name is ' + eachContact.Name + ', each contact email: ' + eachContact.Email);
                }
            } else {
                system.debug('***** NO contacts for this account.****');
            }
            system.debug('----');
        }
    }


    //fetch all departments and its employees
    public static void showParentToChild2() {
        list<department__c> listDept = [select id, name__c, Short_Code__c, (select first_name__c, last_name__c, country__c, salary__c from employees__r) from department__c];
        
        for (Department__c eachDept : listDept) {
            system.debug('department name : ' + eachDept.Name__c + ', Short Code is ' + eachDept.Short_Code__c);

            List<Employee__c> listEmps = eachDept.Employees__r;
            Decimal totalSalary = 0;
            for (Employee__c eachEmp : listEmps) {
                system.debug('--> employee name is ' + eachEmp.First_Name__c + ' ' + eachEmp.Last_Name__c);
                system.debug('--> employee country and salary : ' + eachEmp.Country__c + ' ' + eachEmp.Salary__c);
                totalSalary += eachEmp.Salary__c;
            }
            system.debug('** total salary for ' + eachDept.Name__c + ' department is ' + totalSalary);
            system.debug('----');
        }
    }

    public static list<account> showAccount(string filterIndustry) {
        list<account> filterAccounts = [select name, phone, website, industry, annualrevenue from account where Industry = :filterIndustry];

        return filterAccounts;
    }
    
}